name: GitHub CI

on: workflow_dispatch 

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-2022
        env:
            BUILD_PROJECT: llvm
            BUILD_MASTER: false
            LLVM_VERSION: 18.1.8

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   msvcrt
                -   libcmt

                TARGET_CPU:
                -   x86
                -   amd64

                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Install
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\install.bat

        -   name: Build and test
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\build.bat
                echo ::set-output name=DEPLOY_FILE::%DEPLOY_FILE%

        -   name: Release
            uses: softprops/action-gh-release@v1
            env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            with:
                files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
                tag_name: v${{ github.run_number }}
