name: Build LLVM 18

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-llvm:
    runs-on: windows-latest
    timeout-minutes: 360  # Allow for a longer build time (6 hours)
    
    steps:
    - name: Install dependencies
      run: |
        choco install -y cmake ninja llvm
        
    - name: Download LLVM 18 source
      run: |
        git clone --recurse-submodules --branch release/18.x https://github.com/llvm/llvm-project.git 
        if ($LASTEXITCODE -ne 0) {
          git clone ---recurse-submodules --branch llvmorg-18.0.0 https://github.com/llvm/llvm-project.git
        }
        if ($LASTEXITCODE -ne 0) {
          git clone --recurse-submodules https://github.com/llvm/llvm-project.git
        }
        
    - name: Configure LLVM
      run: |
        mkdir llvm-build
        cd llvm-build
        cmake -G Ninja ..\llvm-project\llvm `
          -DLLVM_ENABLE_Z3_SOLVER=ON `
          -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld" `
          -DLLVM_FORCE_BUILD_RUNTIME=ON `
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" `
          -DLLVM_ENABLE_DUMP=ON `
          -DLLVM_ENABLE_LIBCXX=ON `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_C_COMPILER=clang `
          -DCMAKE_CXX_COMPILER=clang++ `
          -DLLVM_ENABLE_PROJECTS="clang" `
          -DLLVM_TARGETS_TO_BUILD="X86" `
          -DLLVM_OPTIMIZED_TABLEGEN=ON `
          -DLLVM_USE_LINKER=lld `
          -DLLVM_INCLUDE_TESTS=OFF `
          -DLLVM_INCLUDE_EXAMPLES=OFF `
          -DLLVM_INCLUDE_BENCHMARKS=OFF `
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\llvm-install"

    - name: Build LLVM
      run: |
        cd llvm-build
        ninja -j2  # Limit parallelism to avoid memory issues
        
    - name: Install LLVM
      run: |
        cd llvm-build
        ninja install
        
    - name: Upload LLVM build
      uses: actions/upload-artifact@v4
      with:
        name: llvm-18-build
        path: ${{ github.workspace }}\llvm-install
